//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class FileProcessor
{
	public virtual string FilePath
	{
		get;
		set;
	}

	public abstract Asml-MHS-ModelingProject1::System::Collections::Generic::List<Target‎> ProcessFile();

	public FileProcessor()
	{
	}

}

