//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class FileProcessorFactory
{
	private static Asml-MHS-ModelingProject1::TargetManagement::TargetFileProcessors::FileProcessorFactory _instance;

	private FileProcessorFactory()
	{
	}

	public static Asml-MHS-ModelingProject1::TargetManagement::TargetFileProcessors::FileProcessorFactory GetInstance()
	{
		throw new System.NotImplementedException();
	}

	private ~FileProcessorFactory()
	{
	}

	public virtual void Dispose()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void Dispose(bool dispose_others)
	{
		throw new System.NotImplementedException();
	}

	public virtual Asml-MHS-ModelingProject1::TargetManagement::TargetFileProcessors::FileProcessor Create(string filePath)
	{
		throw new System.NotImplementedException();
	}

}

