//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class IniProcessor : FileProcessor
{
	private static string _invalid_ini_format_message;

	public virtual InvalidIniFormat InvalidIniFormat
	{
		get;
		set;
	}

	public IniProcessor(string fp)
	{
	}

	public override Asml-MHS-ModelingProject1::System::Collections::Generic::List<Target‎> ProcessFile()
	{
		throw new System.NotImplementedException();
	}

	private void TargetSetPositionValue(Asml-MHS-ModelingProject2::TargetManagement::Target _current_target, string key, string value)
	{
		throw new System.NotImplementedException();
	}

	private void TargetSetFriend(Asml-MHS-ModelingProject2::TargetManagement::Target _current_target, string value)
	{
		throw new System.NotImplementedException();
	}

	private bool lineMatches(string trimedLine)
	{
		throw new System.NotImplementedException();
	}

}

