//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class InvalidIniFormat
{
	public InvalidIniFormat()
	{
	}

	public InvalidIniFormat(string message)
	{
	}

	public InvalidIniFormat(string message, Asml-MHS-ModelingProject1::System::Exception inner)
	{
	}

	protected InvalidIniFormat(Asml-MHS-ModelingProject1::System::Runtime::Serialization::SerializationInfo info, Asml-MHS-ModelingProject1::System::Runtime::Serialization::StreamingContext context)
	{
	}

}

