//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class MissileLauncherAdapter
{
	public virtual Asml-MHS-ModelingProject1::System::Double Phi
	{
		get;
		private set;
	}

	public virtual Asml-MHS-ModelingProject1::System::Double Theta
	{
		get;
		private set;
	}

	private Asml-MHS-ModelingProject1::TurretManagement::TurretManager m_launcher;

	public MissileLauncherAdapter()
	{
	}

	public virtual void Reset()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Fire()
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveTo(Asml-MHS-ModelingProject1::System::Double phi, Asml-MHS-ModelingProject1::System::Double theta)
	{
		throw new System.NotImplementedException();
	}

	public virtual void MoveBy(Asml-MHS-ModelingProject1::System::Double phi, Asml-MHS-ModelingProject1::System::Double theta)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Dispose()
	{
		throw new System.NotImplementedException();
	}

	protected virtual void Dispose(bool dispose_others)
	{
		throw new System.NotImplementedException();
	}

	private ~MissileLauncherAdapter()
	{
	}

}

