//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class OperationsManager
{
	public virtual Asml-MHS-ModelingProject2::System::Collections::ObjectModel::ObservableCollection<Target> TargetInfo
	{
		get;
		set;
	}

	public virtual int NumberMissiles
	{
		get;
		set;
	}

	private static Asml-MHS-ModelingProject2::OperationsManager::OperationsManager _rules_them_all;

	private Asml-MHS-ModelingProject2::TargetManagement::TargetManager _target_manager;

	private Asml-MHS-ModelingProject2::ASMLEngineSdk::IMissileLauncher _turret;

	private static object MAX_MISSILES;

	public virtual TurretManager TurretManager
	{
		get;
		set;
	}

	public virtual TargetManager TargetManager
	{
		get;
		set;
	}

	public virtual AbstractSearch AbstractSearch
	{
		get;
		set;
	}

	public virtual VideoMgr VideoMgr
	{
		get;
		set;
	}

	public static Asml-MHS-ModelingProject2::OperationsManager::OperationsManager GetInstance()
	{
		throw new System.NotImplementedException();
	}

	private ~OperationsManager()
	{
	}

	public virtual void Dispose()
	{
		throw new System.NotImplementedException();
	}

	private void Dispose(bool dispose_others)
	{
		throw new System.NotImplementedException();
	}

	private OperationsManager()
	{
	}

	public virtual void TurretMoveLeft()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurretMoveRight()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurretMoveUp()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurretMoveDown()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurretFire()
	{
		throw new System.NotImplementedException();
	}

	public virtual void TurretReset()
	{
		throw new System.NotImplementedException();
	}

	public virtual void LoadFile(string targetfile)
	{
		throw new System.NotImplementedException();
	}

	public virtual void ReloadTurret()
	{
		throw new System.NotImplementedException();
	}

	public virtual void LocatedTarget(int x, int y, int z, bool friend)
	{
		throw new System.NotImplementedException();
	}

}

