//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class ProcessorTest
{
	public virtual void IniTest()
	{
		throw new System.NotImplementedException();
	}

	public virtual void IniTestReject()
	{
		throw new System.NotImplementedException();
	}

	public virtual void XmlTest()
	{
		throw new System.NotImplementedException();
	}

	public virtual void XmlTestReject()
	{
		throw new System.NotImplementedException();
	}

	public ProcessorTest()
	{
	}

}

