//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

internal class XMLProcessor : FileProcessor
{
	public XMLProcessor(string fp)
	{
	}

	public override Asml-MHS-ModelingProject1::System::Collections::Generic::List<Target‎> ProcessFile()
	{
		throw new System.NotImplementedException();
	}

	private void SetTargetFriend(Asml-MHS-ModelingProject2::TargetManagement::Target _current_target, string attribute_value)
	{
		throw new System.NotImplementedException();
	}

	private void SetTargetPositionValue(Asml-MHS-ModelingProject2::TargetManagement::Target _current_target, string attribute_name, string value)
	{
		throw new System.NotImplementedException();
	}

}

